yamlItem1: [{desc: desc of yamlItem1, cid: yamlItem1},  yamlItem1]
loca: locaYaml
msg: Hello from Yaml
f3: '`function(){ paste("config.yml.f3: local=",loca,", subItem1=",paste(cid("subItem1"),collapse=","),sep="") }`'
ev2: 'subItem1=`paste(cid("subItem1"),collapse=",")`'
